# !/bin/bash
#
# Generate the game executable for Linux platform.
#
# Author: Edson Alves - edsonalves@unb.br
# Date: 09/03/2017

# System
SYSTEM=linux

# Directories
BIN_DIR=bin
SRC_DIR=src
LIB_DIR=lib
BUILD_DIR=build

SYSTEM_BIN_DIR=$BIN_DIR/$SYSTEM
SYSTEM_LIB_DIR=$LIB_DIR/$SYSTEM
SYSTEM_BIN_LIB_DIR=$SYSTEM_BIN_DIR/lib
SYSTEM_BUILD_DIR=$BUILD_DIR/$SYSTEM

SDL_DIR=$SYSTEM_LIB_DIR/SDL2
SDL_LIB_DIR=$SDL_DIR/lib

READLINE_DIR=$SYSTEM_LIB_DIR/readline
READLINE_LIB_DIR=$READLINE_DIR/lib

TERMCAP_DIR=$SYSTEM_LIB_DIR/termcap
TERMCAP_LIB_DIR=$TERMCAP_DIR/lib

LUA_DIR=$SYSTEM_LIB_DIR/lua
LUA_LIB_DIR=$LUA_DIR/lib

mkdir -p $BUILD_DIR/$SYSTEM $BIN_DIR/$SYSTEM/lib
cd $BUILD_DIR/$SYSTEM
pwd
cmake ../.. -DCMAKE_TOOLCHAIN_FILE=../../linux/Linux.cmake
make
cd ../..
cp $SYSTEM_BUILD_DIR/$SRC_DIR/Dauphine $SYSTEM_BIN_DIR
cp $SYSTEM_BUILD_DIR/$LIB_DIR/TmxParser/libtmxparser.a $LIB_DIR/TmxParser/
cp $SDL_LIB_DIR/libSDL2-2.0.so $SYSTEM_BIN_LIB_DIR
cp $SDL_LIB_DIR/libSDL2_image-2.0.so.0 $SYSTEM_BIN_LIB_DIR
cp $SDL_LIB_DIR/libSDL2_ttf-2.0.so.0 $SYSTEM_BIN_LIB_DIR
cp -f $READLINE_LIB_DIR/libreadline.so.7 $SYSTEM_BIN_LIB_DIR
cp -f $READLINE_LIB_DIR/libhistory.so.7 $SYSTEM_BIN_LIB_DIR
cp $TERMCAP_LIB_DIR/libtermcap.a $SYSTEM_BIN_LIB_DIR
cp $LUA_LIB_DIR/liblua.a $SYSTEM_BIN_LIB_DIR
